### ISSUE TITLE
Comment utiliser la version de Github ?

### ISSUE THREAD

**Issue by tubiana** [james-elliot/iris#1]
Bonjour! 

J'aimerais pouvoir utiliser ce que vous avez développé pour trouver les IRIS d'adresses que j'ai dans un fichier CSV (au bon format , je pense): exemple
``` 
N_PATIENT;PST_ADRESSE;PST_CP;PST_VILLE
1; 1 Rue Kleber; 33200; Bordeaux
2; 50 Rue de Turenne; 75003; Paris
``` 

Cependant, il semble que le logiciel ait besoin d'un fichier "adresses-france.csv" 
Ne sachant pas trop j'ai pris celui situé ici : https://adresse.data.gouv.fr/data/ban/adresses/latest/csv/

Cependant il ne trouve pas les adresse. Est-ce qu'il y a un format spécifique à avoir ? Les adresses  : 
```
Addresses database read in 34.714147753s
Iris database built in 3.585436458s
Patient { N_PATIENT: "1", PST_ADRESSE: " 1 Rue Kleber", PST_CP: " 33200", PST_VILLE: " Bordeaux" }
normalized: 1 rue kleber 0  bordeaux
Searched for 15.448485ms
Address not found
Patient { N_PATIENT: "2", PST_ADRESSE: " 50 Rue de Turenne", PST_CP: " 75003", PST_VILLE: " Paris" }
normalized: 50 rue de turenne 0  paris
Searched for 28.3µs
Address not found
Patient { N_PATIENT: "3", PST_ADRESSE: " 51 Rue de Turenne", PST_CP: " 75003", PST_VILLE: " Paris" }
normalized: 51 rue de turenne 0  paris
Searched for 21.92µs
Address not found
Job done in 26.779147ms
```

Est-ce qu'il y a un autre formatage à appliquer ou bien est-ce le fichier "adresses-france.csv" doit être différent ?

Merci pour votre aide :)

**Comment by james-elliot** [comment]
Bonjour,
J'ai remis à jour le readme pour qu'il soit plus clair. Il indique sans doute plus clairement les adresses des deux fichiers à télécharger, celui des adresses et celui des coordonnées en format Shapefile de la base IRIS de l'INSEE.

**Comment by tubiana** [comment]
Merci beaucoup C'est plus clair en effet! 
ça fonctionne du tonnerre =D
